myportfolio/accounts/urls.py
from django.conf.urls import url,include
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^$',views.Mainpage,name='mainapp'),
    url(r'^login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),

    url(r'^logout/',
        auth_views.LogoutView.as_view(),
        name='logout'),

    url(r'^signup/',
        views.SignUp.as_view(),
        name='signup'),
]

myportfolio/myportfolio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from accounts import views as acc_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portfolio/$', views.HomePage.as_view(),name='portfolio'),
    url(r'^$', views.Mainpage,name='main'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^resto/', include('restorecommand.urls',namespace='resto')),
    url(r'^interview/', include('interview.urls',namespace='interview')),
    url(r'^test/$', views.TestPage.as_view(),name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(),name='thanks'),
]

myportfolio/restorecommand/urls.py
from django.conf.urls import url

from . import views

app_name='restorecommand'

urlpatterns = [
    url(r'^$', views.index,name='resto_index'),
    url(r'^search/$', views.newRestaurants,name='search_res'),
    url(r'^(?P<restaurant_id>\d+)/delete/$', views.deleteRestaurants,name='delete_res'),
    url(r'^(?P<restaurant_id>\d+)/edit/$', views.editRestaurants,name='edit_res'),
    url(r'^add/$', views.addRestaurants,name='add_res'),
    url(r'^restaurants/$', views.showRestaurants,name='restaurants'),
]

myportfolio/restorecommand/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Restaurant(models.Model):
    id = models.IntegerField(primary_key = True)
    name = models.CharField(max_length = 1000)
    address = models.TextField(max_length = 1000)
    image = models.CharField(max_length = 1000)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("resto_index")

    def __str__(self):
        return self.name
  # #Add a property decorator to serialize information from this database
  # @property
  # def serialize(self):
  #   return {
  #     'name': self.name,
  #     'address': self.address,
  #     'image' : self.image,
  #     'id' : self.id
  #     }

class Query(models.Model):
    location = models.CharField(max_length=1000)
    mealType = models.CharField(max_length=1000)

myportfolio/restorecommand/forms.py
from django import forms

from .models import Restaurant,Query

class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ('location','mealType')


class RestaurantForm(forms.ModelForm):

    class Meta:
        model = Restaurant
        fields = ('id','name', 'address','image')

myportfolio/restorecommand/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .models import Restaurant,Query
from .forms import RestaurantForm,QueryForm

from .findARestaurant import findARestaurant,findAllRestaurant

@login_required
def index(request):
    if request.method == 'GET':
  # 		RETURN ALL RESTAURANTS IN DATABASE
        restaurants = findAllRestaurant()
        return render(request,'restorecommand/restorecommand_index.html',{'restaurants': restaurants})

@login_required
def showRestaurants(request):
    if request.method == 'GET':
        restaurants = Restaurant.objects.all()
        return render(request,'restorecommand/restaurants.html', {'restaurants': restaurants})


@login_required
def newRestaurants(request):
    if request.method == "POST":
        form = QueryForm(request.POST)
        if form.is_valid():

            location = form.cleaned_data['location']
            mealType = form.cleaned_data['mealType']

            # use this information
            restaurant_info = findARestaurant(mealType, location)
            return render(request,'restorecommand/restaurants.html', {'restaurants': restaurant_info})
    else:
        form = QueryForm()
    return render(request, 'restorecommand/newRestaurants.html', {'form': form})


@login_required
def addRestaurants(request):
    if request.method == "POST":
        data = request.POST.get('dataabc')
        # data = request.GET.get('dataabc',None)
        print(data)
        # restaurant_info = findARestaurant(restaurant_name, restaurant_address)
        # print(restaurant_info)
        # newRestaurants = Restaurant(name = str(restaurant_info['name']), address = str(restaurant_info['address']), image = restaurant_info['image'])
        #
        # newRestaurants.save()
        restaurants = Restaurant.objects.all()
        return render(request,'restorecommand/restaurants.html', {'restaurants': restaurants})
    else:
        form = QueryForm()
    return render(request, 'restorecommand/newRestaurants.html', {'form': form})

@login_required
def deleteRestaurants(request,restaurant_id):
	restaurantToDelete = Restaurant.objects.filter(id=restaurant_id)
	if request.method == 'POST':
		restaurantToDelete = Restaurant.objects.filter(id=restaurant_id).delete()
		return redirect('restorecommand:restaurants')
	else:
		return render(request,'restorecommand/deleteRestaurants.html',{'restaurant': restaurantToDelete})

@login_required
def editRestaurants(request,restaurant_id):
  editedRestaurant = session.query(Restaurant).filter_by(id = restaurant_id).one()
  if request.method == 'POST':
      if request.form['name']:
        editedRestaurant.name = request.form['name']
        # flash('Restaurant Successfully Edited %s' % editedRestaurant.name)
        return redirect(url_for('showRestaurants'))
  else:
  	return render_template('editRestaurants.html', restaurant = editedRestaurant)

myportfolio/restorecommand/templates/restorecommand/deleteRestaurants.html
{% extends "restorecommand/restorecommand_base.html" %}
{% block content %}

<h2> Are you sure you want to delete {{restaurant.name}}? </h2>

<form action="#" method = 'post'>

	<button type="submit" class="btn btn-default delete" id="submit" type="submit">
	<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete</button>
	<a href = '{% url 'restorecommand:restaurants' %}'>
		{%csrf_token%}
		<button class="btn btn-default delete">
		<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
	</a>

</form>

{% endblock %}

myportfolio/restorecommand/templates/restorecommand/editRestaurants.html
{% extends "main.html" %}
{% block content %}

	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner menu">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>Edit {{restaurant.name}}</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-1 padding-top">
			<form action="{{ url_for('editRestaurants',restaurant_id = restaurant.id)}}" method = "post">
				<div class="form-group">
					<label for="name">Name:</label>
					<input type ="text" class="form-control" name="name" value="{{restaurant.name }}">
					<div class="padding-bottom"></div>

					<button type="submit" class="btn btn-default" id="submit" type="submit">
					<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Save</button>


				</div>
			</form>
			<a href = "{{url_for('showRestaurants')}}">
						<button class="btn btn-default delete">
						<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
					</a>
		</div>
	</div>
{% endblock %}

myportfolio/restorecommand/templates/restorecommand/map.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.');
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUJudz988uTkWCX3TlAZoWNANwU1sfdug&callback=initMap">
    </script>
  </body>
</html>

myportfolio/restorecommand/templates/restorecommand/newRestaurants.html
{% extends "restorecommand/restorecommand_base.html" %}
{% block content %}

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>

	<div class="row banner menu">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>Search Restaurant</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-1 padding-top">
			<form action="#" method = "post">

				<div class="form-group">
          {%csrf_token%}
          {{ form.as_p }}

				<div class="padding-bottom"></div>
				<button type="submit" class="btn btn-default" id="submit" type="submit">
				<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Search</button>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

myportfolio/restorecommand/templates/restorecommand/restaurants.html
{% extends "restorecommand/restorecommand_base.html" %}

{% block content %}

	<div class="row top-menu">
		<div class="col-md-10"></div>
		<div class="col-md-2 text-right"></div>
	</div>
	<div class="row divider blue">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner main">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			<h1>Restaurants</h1>
		</div>
	</div>

	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-10 padding-none">
			<a href="{% url 'restorecommand:search_res' %}">
				<button class="btn btn-default" id="new-restaurant">
					<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Search
				</button>
			</a>
		</div>
		<div class="col-md-1"></div>
	</div>

	{% for restaurant in restaurants %}
		<a href="#">
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10 restaurant-list">
						<h3>{{restaurant.name}}</h3>
						<h4>{{restaurant.address}}<h4>

		<a href="{% url 'restorecommand:add_res'%}">
			<button class="btn btn-default" id="add-restaurant_{{restaurant.id}}">
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Add
			</button>
		</a>

		<a href="#">
			<button class="btn btn-default" id="edit-restaurant_{{restaurant.id}}" name="{{restaurant.id}}_{{restaurant.name}}">
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Edit
			</button>
		</a>

		<a href="#">
			<button class="btn btn-default" id="delete-restaurant_{{restaurant.id}}">
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Delete
			</button>
		</a>
				</div>
				<div class="col-md-1"></div>
			</div>
		</a>


	{% endfor %}

	<script type="text/javascript">

	$(document).ready(function() {
		$('.btn').each(function(){
				var toggle_div_id = $(this).attr('name');
				$(this).click(function(){

						var datax = {'dataabc': toggle_div_id};
						console.log(datax)
						$.ajax({
								url: "{% url 'restorecommand:add_res' %}",
								method: "POST",
								headers: {'X-CSRFToken': '{{ csrf_token }}'},
								data: datax,
								dataType: "json"
							}).done(function(response) {
								console.log(response.id + " " + response.name);
							}).fail(function (error) {
								console.log(error);
							});
				});
		});
	});
	</script>
{% endblock %}

myportfolio/restorecommand/templates/restorecommand/restorecommand_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Restaurant recommendation</title>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script
src="https://code.jquery.com/jquery-3.1.1.min.js"
integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
crossorigin="anonymous"></script>

{# Fonts#}
<link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/styles.css' %}">



  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'restorecommand:resto_index'%}">Restaurant 4U</a>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'main'%}">Projects</a></li>
          <li><a href="{% url 'portfolio'%}">Portfolio</a></li>  
          {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:logout' %}"> Log Out</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}"> Log Out</a></li>
          <li><a href="{% url 'accounts:signup' %}"> Sign Up</a></li>
        </ul>
      </div>
        {% endif %}
    </nav>

    <div class="container mycontent">
      {% block content%}
      {% endblock %}
    </div>

      <div id="map"></div>


    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // Try HTML5 geolocation.

          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            console.log(pos);
            infoWindow.setContent('Location found.');
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        };

    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUJudz988uTkWCX3TlAZoWNANwU1sfdug&callback=initMap">
    </script>


  </body>
</html>

myportfolio/restorecommand/templates/restorecommand/restorecommand_index.html
{% extends "restorecommand/restorecommand_base.html" %}
{% block content %}


    <div class="row top-menu">
		<div class="col-md-10"></div>
		<div class="col-md-2 text-right"></div>
	</div>
	<div class="row divider blue">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner main">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			<h1>Restaurants</h1>
		</div>
	</div>

	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-10 padding-none">
			<a href="{% url 'restorecommand:search_res'%}">
				<button class="btn btn-default" id="new-restaurant">
					<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Search Restaurants
				</button>
			</a>
		</div>
		<div class="col-md-1"></div>
	</div>

  In this example, I used the RestAPI of Foursquare to create a restaurant recommendation application.
  You can push the Search Restaurants button and type in your favorite food and your place, it will return
  the restaurants near your place. Have fun!! 
<!--
	{% for restaurant in restaurants %}
		<a href="#">
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10 restaurant_list" id="restaurant_list">
						<h3>{{restaurant.name}}</h3>
						<h4>{{restaurant.address}}<h4>

						<a href="#">
			<button class="btn btn-default" id="add-restaurant_{{restaurant.id}}">
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Add
			</button>
		</a>
						<a href="#">
			<button class="btn btn-default" id="delete-restaurant_{{restaurant.id}}">
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>Delete
			</button>
		</a>
				</div>
				<div class="col-md-1"></div>
			</div>
		</a>

		{% endfor %} -->
    <!-- <script type="text/javascript">

    $(document).ready(function() {
      $('.btn').each(function(){
          var toggle_div_id = $(this).attr('id');
          $(this).click(function(){

              var datax = JSON.stringify({'dataabc': toggle_div_id});
              console.log(datax)
              $.ajax({
                  url: "{% url 'restorecommand:add_res' %}",
                  method: "POST",
                  headers: {'X-CSRFToken': '{{ csrf_token }}'},
                  data: datax,
                  dataType: "json"
                }).done(function(response) {
                  console.log(response.id + " " + response.name);
                }).fail(function (error) {
                  console.log(error);
                });
          });
      });
    });
    </script> -->
{% endblock %}