myportfolio/accounts/urls.py
from django.conf.urls import url,include
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^$',views.Mainpage,name='mainapp'),
    url(r'^login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),

    url(r'^logout/',
        auth_views.LogoutView.as_view(),
        name='logout'),

    url(r'^signup/',
        views.SignUp.as_view(),
        name='signup'),
]

myportfolio/interview/urls.py
from django.conf.urls import url

from . import views

app_name='interview'

urlpatterns = [
    url(r'^$', views.index,name='interview_index'),
    url(r'^add/$', views.addQuestion,name='interview_add'),
    url(r'^all/$', views.allQuestion,name='interview_all'),
    url(r'^test/$', views.testQuestion,name='interview_test'),
    url(r'^(?P<question_id>\d+)/next/$', views.nextQuestion,name='interview_next'),
    url(r'^(?P<question_id>\d+)/delete/$', views.deleteQuestion,name='interview_delete'),
    url(r'^(?P<question_id>\d+)/edit/$', views.editQuestion,name='interview_edit'),
]

myportfolio/myportfolio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from accounts import views as acc_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portfolio/$', views.HomePage.as_view(),name='portfolio'),
    url(r'^$', views.Mainpage,name='main'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^resto/', include('restorecommand.urls',namespace='resto')),
    url(r'^interview/', include('interview.urls',namespace='interview')),
    url(r'^test/$', views.TestPage.as_view(),name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(),name='thanks'),
]

myportfolio/interview/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Question(models.Model):
    id = models.IntegerField(primary_key = True)
    question = models.TextField()
    answer = models.TextField(default="")
    BOOL_CHOICES = ((True, 'job'), (False, 'nationality'))
    option = models.BooleanField(choices=BOOL_CHOICES,default=False)

    def get_absolute_url(self):
        return reverse("interview:interview_all")

myportfolio/interview/forms.py
from django import forms
from django.forms.widgets import RadioSelect
from .models import Question

class QuestionForm(forms.ModelForm):
    BOOL_CHOICES = ((True, 'job'), (False, 'nationality'))
    option = forms.ChoiceField(choices=BOOL_CHOICES, widget=RadioSelect)
    class Meta:
        model = Question
        fields = ('question','answer',)

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['question'].widget.attrs['placeholder'] = 'Add question here'
        self.fields['answer'].widget.attrs['placeholder'] = 'Add answer here'

myportfolio/interview/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from random import randint
import random

from .models import Question
from .forms import QuestionForm
# Create your views here.

@login_required
def index(request):
    if request.method == 'GET':
        return render(request,'interview/interview_index.html')

@login_required
def testQuestion(request):
    if request.method == 'POST':
        job = request.POST.get('job')
        na = request.POST.get('nationality')

        if job:
            questions = Question.objects.filter(option=True)
        elif na:
            questions = Question.objects.filter(option=False)
        else:
            questions = Question.objects.all()
        ID = [question.id for question in questions]
        rand_entities = randint(0, len(ID)-1)

        questions = Question.objects.filter(id=ID[rand_entities])
        return render(request,'interview/interview_test.html', {'questions': questions})
    else:
        return render(request,'interview/interview_index.html')

@login_required
def nextQuestion(request,question_id):
    questions = Question.objects.filter(id=question_id)
    option = [question.option for question in questions]
    print(type(option))
    if request.method == 'GET':
        questions = Question.objects.filter(option=option[0])
        ID = [question.id for question in questions]
        rand_entities = randint(0, len(ID)-1)

        questions = Question.objects.filter(id=ID[rand_entities])
        return render(request,'interview/interview_test.html', {'questions': questions})
    else:
        questions = Question.objects.filter(option=option)
        ID = [question.id for question in questions]
        rand_entities = randint(0, len(ID)-1)

        questions = Question.objects.filter(id=ID[rand_entities])
        print('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        return render(request,'interview/interview_next.html', {'questions': questions})


@login_required
def addQuestion(request):
    if request.method == "POST":
        job = request.POST.get('job')
        na = request.POST.get('nationality')

        question = request.POST.get('question')
        answer = request.POST.get('answer')

        if job is True:
            option = True
        elif na is True:
            option = False


        newquestion = Question(question = str(question),answer = str(answer),option = option)

        newquestion.save()
        questions = Question.objects.all()
        return render(request,'interview/interview_all.html', {'questions': questions})
    else:
        return render(request,'interview/interview_add.html')

@login_required
def allQuestion(request):
    if request.method == 'GET':
        questions = Question.objects.all()
        return render(request,'interview/interview_all.html', {'questions': questions})


@login_required
def deleteQuestion(request,question_id):
    questionToDelete = Question.objects.filter(id=question_id)
    print(questionToDelete)
    if request.method == 'POST':
        questionToDelete = Question.objects.filter(id=question_id).delete()
        questions = Question.objects.all()
        return render(request,'interview/interview_all.html', {'questions': questions})
    else:
        return render(request,'interview/interview_delete.html',{'questions': questionToDelete})


@login_required
def editQuestion(request,question_id):
    questionToEdit = Question.objects.filter(id=question_id)
    if request.method == "POST":

        job = request.POST.get('job')
        na = request.POST.get('nationality')

        newquestion = request.POST.get('question')
        newanswer = request.POST.get('answer')

        if job is True:
            newoption = True
        else:
            newoption = False

        Question.objects.filter(id=question_id).update(question = str(newquestion))
        Question.objects.filter(id=question_id).update(answer = str(newanswer))
        Question.objects.filter(id=question_id).update(option = newoption)

        questions = Question.objects.all()
        return render(request,'interview/interview_all.html', {'questions': questions})
    else:
        return render(request,'interview/interview_edit.html', {'questions': questionToEdit})

myportfolio/interview/templates/interview/interview_add.html
{% extends "interview/interview_base.html" %}
{% block content %}

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>

	<div class="row banner menu">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>Add Question</h1>
		</div>
	</div>

<br>


	<form action= "{% url 'interview:interview_add'%}" method="POST" >
	{% csrf_token %}
	<label for="question">Question:</label><input type="text" name="question" value="" style="font-size:12pt;height:80px;width:1000px;">
	<br>
	<label for="answer">Answer:</label><input type="text" name="answer" value="" style="font-size:12pt;height:80px;width:1000px;">
	<br>
	<br>
	<input type="checkbox" name="job">Job<br>
	<input type="checkbox" name="nationality">Nationality<br>
	<input class="btn btn-default" type="submit" value="Take the test" />
	</form>

  <br>

{% endblock %}

myportfolio/interview/templates/interview/interview_all.html
{% extends "interview/interview_base.html" %}
{% block content %}

<h1> This is the index page of interview application</h1>

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>
<br>
<br>
<a href="{% url 'interview:interview_add'%}">
  <button class="btn btn-default" id="next-question">Add Question
  </button>
</a>

<a href="{% url 'interview:interview_all'%}">
  <button class="btn btn-default" id="next-question">All Question
  </button>
</a>
<br>
<br>
{% for question in questions %}
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10 restaurant-list">
          <h3>{{question.question}}</h3>


  <a href="{% url 'interview:interview_delete' question_id=question.id %}">
    <button class="btn btn-default" id="next-question">Delete</button>
  </a>

  <a href="{% url 'interview:interview_edit' question_id=question.id %}">
    <button class="btn btn-default" id="next-question">Edit</button>
  </a>
	  <button class="btn btn-default toggle button" id="button_{{question.id}}">Show/Hide Answer</button>
		<br>
		<div class="answer" id="answer_button_{{question.id}}">
			<h5>{{question.answer}}</h5>
		</div>


      </div>
      <div class="col-md-1"></div>
    </div>



{% endfor %}

<script type="text/javascript">
$(document).ready(function() {
	$('.answer').hide();

	$('.button').each(function(){
			var toggle_div_id = "answer_" + $(this).attr('id');
			$(this).click(function(){
				console.log(toggle_div_id)
					$('#'+toggle_div_id).toggle();
			});
	});

	$('.toggle_{{question.id}}').click(function(){
		$('.answer_{{question.id}}').toggle();
	});
});
</script>
{% endblock%}

myportfolio/interview/templates/interview/interview_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Interview Simulation</title>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script
src="https://code.jquery.com/jquery-3.1.1.min.js"
integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
crossorigin="anonymous"></script>

{# Fonts#}
<link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/styles.css' %}">



  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'interview:interview_index'%}">Interview</a>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'main'%}">Projects</a></li>
          <li><a href="{% url 'portfolio'%}">Portfolio</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:logout' %}"> Log Out</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}"> Log Out</a></li>
          <li><a href="{% url 'accounts:signup' %}"> Sign Up</a></li>
        </ul>
      </div>
        {% endif %}
    </nav>

    <div class="container mycontent">
      {% block content%}
      {% endblock %}
    </div>


  </body>
</html>

myportfolio/interview/templates/interview/interview_delete.html
{% extends "interview/interview_base.html" %}
{% block content %}

{% for question in questions %}
<h2> Are you sure you want to delete question ? </h2>
<h2>{{question.question}}</h2>
<form action="#" method = 'post'>

	<button type="submit" class="btn btn-default delete" id="submit" type="submit">
	<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete</button>
	<a href = '{% url "interview:interview_delete"  question_id=question.id %}'>
		{%csrf_token%}
		<button class="btn btn-default delete">
		<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
	</a>

</form>

{% endfor %}

{% endblock %}

myportfolio/interview/templates/interview/interview_edit.html
{% extends "interview/interview_base.html" %}
{% block content %}

	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner menu">
		<div class="col-md-11 col-md-offset-1 padding-none">
      {%for question in questions %}
			<h1>Edit question "{{question.question}}"</h1>
		</div>
	</div>

      <div class="row container">
    		<div class="col-md-6 col-md-offset-1 padding-top">
					<form action= "{% url 'interview:interview_edit' question_id=question.id%}" method="POST" class="form-group">
					{% csrf_token %}
					<label for="question">Question:</label>
					<input type="text" name="question" value="" style="font-size:12pt;height:80px;width:1000px;" placeholder= "{{question.question}}">
					<br>
					<br>
					<br>
					<label for="answer">Answer:</label><input type="text" name="answer" value="" style="font-size:12pt;height:80px;width:1000px;" placeholder= "{{question.answer}}">
					<br>
					<br>
					<input type="checkbox" name="job">Job<br>
					<input type="checkbox" name="nationality">Nationality<br>
					<input class="btn btn-default" type="submit" value="Edit" />
					</form>
    		</div>
    	</div>
{% endfor %}
{% endblock %}

myportfolio/interview/templates/interview/interview_index.html
{% extends "interview/interview_base.html" %}
{% block content %}

<h1> This is the index page of interview application</h1>

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>
<br>
<br>

<a href="{% url 'interview:interview_all'%}">
  <button class="btn btn-default" id="next-question">All Question
  </button>
</a>
<br>
<br>

<form action= "{% url 'interview:interview_test'%}" method="POST" >
{% csrf_token %}
<input class="btn btn-default" type="submit" value="Take the test" />
<br>
<br>
<input type="checkbox" name="job">Job<br>
<input type="checkbox" name="nationality">Nationality<br>

</form>

{% endblock%}

myportfolio/interview/templates/interview/interview_next.html
{% extends "interview/interview_base.html" %}
{% block content %}

<h1> This is the index page of interview application</h1>

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>
<br>
<br>
<a href="{% url 'interview:interview_add'%}">
  <button class="btn btn-default" id="next-question">Add Question
  </button>
</a>

<a href="{% url 'interview:interview_all'%}">
  <button class="btn btn-default" id="next-question">All Question
  </button>
</a>
<br>
<br>
{% for question in questions %}
  <a href="#">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10 restaurant-list">

          <h3>{{question.id}}. {{question.question}}</h3>

  <a href="{% url 'interview:interview_next' option=question.option %}">
    <button class="btn btn-default" id="next-question">Next</button>
  </a>
  <button class="btn btn-default" id="next-question">Show/Hide Answer</button>

	<a href="{% url 'interview:interview_edit' question_id=question.id %}">
    <button class="btn btn-default" id="next-question">Edit</button>
  </a>

	<br>
	<br>
  <h3>{{question.answer}}</h3>
      </div>
      <div class="col-md-1"></div>
    </div>
  </a>


{% endfor %}
{% endblock%}

myportfolio/interview/templates/interview/interview_test.html
{% extends "interview/interview_base.html" %}
{% block content %}

<h1> This is the index page of interview application</h1>

<div class="row divider green">
	<div class="col-md-12">
	</div>
</div>
<br>
<br>
<a href="{% url 'interview:interview_add'%}">
  <button class="btn btn-default" id="next-question">Add Question
  </button>
</a>

<a href="{% url 'interview:interview_all'%}">
  <button class="btn btn-default" id="next-question">All Question
  </button>
</a>
<br>
<br>
{% for question in questions %}
  <a href="#">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10 restaurant-list">

          <h3>{{question.id}}. {{question.question}}</h3>

  <a href="{% url 'interview:interview_next' question_id=question.id %}">
    <button class="btn btn-default" id="next-question">Next Question</button>
  </a>
  <button class="btn btn-default toggle" id="toggle-answer">Show/Hide Answer</button>
	<a href="{% url 'interview:interview_edit' question_id=question.id %}">
    <button class="btn btn-default" id="next-question">Edit</button>
  </a>

	<br>
	<br>
	<div class="answer">
		<h3>{{question.answer}}</h3>
	</div>

      </div>
      <div class="col-md-1"></div>
    </div>
  </a>


{% endfor %}
<script type="text/javascript">
$(document).ready(function() {
	$('.answer').hide();
	$('.toggle').click(function(){
		$('.answer').toggle();
	});
});
</script>
{% endblock%}